### PR TITLE
build: add node-gyp as a dependency

### PR DESCRIPTION
**Pull request by mmarchini**
Fixes: https://github.com/nodejs/llnode/issues/355

Signed-off-by: Matheus Marchini <mmarchini@netflix.com>

### CODE REVIEW

**Comment by bnoordhuis** [comment]
As a maintainer of node-gyp, depending on a specific version of node-gyp is something I advise against. You should normally use the one that's bundled with node+npm.

**Comment by mmarchini** [comment]
Thanks for the feedback @bnoordhuis, I'll probably not merge this then.

Any suggestions on #355? Or is it a situation we just can't handle in code, since it's caused by Ubunut/Debian distributing a non-official Node.js package?

**Comment by bnoordhuis** [comment]
#355 seems like a problem of debian or ubuntu's own making. If those distros tracked v8.x LTS like they should have, they'd be at a node-gyp version that's new enough (v5.0.5 vs v3.6.2.)

**Comment by mmarchini** [comment]
Closing in favor of https://github.com/nodejs/llnode/pull/367

**Pull request closed without merging**
