### PR TITLE
[WIP] src: `v8 snapshot` command

### PR DESCRIPTION
**Pull request by mmarchini**
**DO NOT LAND YET**

[P.S.: The code is a mess right now, I'm opening a PR to get feedback on how the feature should look like]

This PR introduces a new command to create a V8 snapshot from a core dump. Right now the snapshot is not fully functional, but it works on Chrome DevTools. The goal is to enable the use of Chrome DevTools alongside llnode.

We still need to address https://github.com/nodejs/llnode/issues/195 and https://github.com/nodejs/llnode/issues/197 before making it work properly. Right now it can be used with the command `v8 snapshot`, which will create a `core.heapsnapshot` in the current working directory. The generated file can be open by Chrome DevTools, but it doesn't show a list of retainers yet.

### CODE REVIEW

**Comment by indutny** [comment]
Neat! Just in case, you may find this helpful: https://github.com/indutny/core2dump (if it is still relevant)

**Comment by mmarchini** [comment]
I found https://github.com/indutny/core2dump when working on this, but couldn't make it work :( (probably because so many things have changed in V8 in the last two years)

**Comment by joyeecheung** [comment]
It would be cool to be able to expose a `toHeapSnapshot()` method in https://github.com/nodejs/llnode/pull/147 I plan to revamp that PR a bit soon to expose structured objects instead of strings.

**Comment by mmarchini** [comment]
Closing since I haven't had the time to move this forward. If anyone wants to work on it, feel free to pick it up! (Although I think this will be much easier to accomplish once our JS API is out of experimental).

**Pull request closed without merging**
