### PR TITLE
WIP - test: Fix the path to llnode plugin

### PR DESCRIPTION
**Pull request by hhellyer**
Load the llnode plugin from the location npm install creates it at.

### CODE REVIEW

**Comment by hhellyer** [comment]
This fix causes `npm test` to load the plugin library from the location `npm install` creates it at. This is probably correct but it is a different location to the location `./gyp_llnode && make -C out/` will use so now the tests fail after building that way. (Previously they worked that way but failed if `npm install` was used to build.)

This gets the test code running on travis but the tests are still failing:
https://travis-ci.org/nodejs/llnode/jobs/249579889
(I'll see if I can figure out why quickly and maybe add another commit to this.)

**Comment by cjihrig** [comment]
> This is probably correct but it is a different location to the location ./gyp_llnode && make -C out/ will use so now the tests fail after building that way.

Would it make sense to try to detect the location in `common.js`, or maybe even use an environment variable to define the location.

**Comment by hhellyer** [comment]
@cjihrig - It might do, there's not that many places to look. I guess the problem is which to pick if both are found. (That could just result in a test failure that reminds you to delete one of them though!)

**Comment by cjihrig** [comment]
We could emit a warning or complain loudly in some other way if they are both found.

**Comment by hhellyer** [comment]
Slightly awkwardly the travis build runs npm install which builds the plugin then runs the _travis make target which runs gyp_llnode and compiles the plugin. This change blocks all the tests running on travis:
https://travis-ci.org/nodejs/llnode/jobs/249994477

I'll figure out what to do next, I have to push the changes to a branch on a PR so that travis picks them up though so I've added a WIP tag to this PR!

**Comment by joyeecheung** [comment]
Travis is now working with the plugin built with `npm install`. Should this be closed, or updated to fallback to the plugin in `out/Release` when there isn't one in the project directory, or something else?

**Comment by bnoordhuis** [comment]
Ping @hhellyer.  Can you update or close?

**Comment by hhellyer** [comment]
I'll close, it's been a bit too long since I looked at this and I'm not in a position to update it at the moment. Sorry for leaving it lying around!

**Pull request closed without merging**
