### PR TITLE
src: introduce Inspector class

### PR DESCRIPTION
**Pull request by mmarchini**
Inspect methods (which are methods to visualize content from an object)
were tightly coupled with object definitions. In fact, the structure of
some objects is defined inside those Inspect methods, making it harder
to reuse code (for example, to return structured objects in our API
instead of strings). This commit is the beginning of a refactor effort
to decouple object visualization and object strucutres in order to
provide simpler code and a more useful API.

Most changes in this commit are moving ::Inspect methods from V8 Object
classes to a separate class Inspector, and changing call sites to use
this new approach. Inspector::Inspect is a single templated method with
specialization for each class it knows how to display.

### CODE REVIEW

**Comment by mmarchini** [comment]
By the way, I might have fixed some warning as well (#245).

**Comment by mmarchini** [comment]
cc @joyeecheung @indutny @cjihrig @bnoordhuis @rnchamberlain @hhellyer @richardlau @Drieger since I don't want this to land unnoticed.

**Comment by joyeecheung** [comment]
Great work! From a glance the approach looks reasonable to me, two things to note:

- The name inspector sort of gave me a false impression that this is implementing the inspector protocol..maybe viewer would be a less ambiguous name, but I don't feel particularly strongly about this
- The linux tests seem to be failing on Travis?

**Comment by mmarchini** [comment]
Renamed `Inspector` to `Printer`, `Inspect*` to `Stringify*` and `InspectOptions` to `PrinterOptions`. I'll try to look into the Linux failures next.

**Comment by mmarchini** [comment]
Seems to be a linking problem:

```
(llnode) v8 inspect 0x255469f99d69
/usr/local/bin/lldb: symbol lookup error: /home/mmarchini/llnode/llnode.so: undefined symbol: _ZN6llnode2v88JSObject16GetInObjectValueIdEET_liRNS_5ErrorE
$ echo "_ZN6llnode2v88JSObject16GetInObjectValueIdEET_liRNS_5ErrorE" | c++filt
double llnode::v8::JSObject::GetInObjectValue<double>(long, int, llnode::Error&)
```

**Comment by mmarchini** [comment]
Fixed by moving `JSObject::GetInObjectValue` implementation to `src/llv8-inl.h`.

**Comment by mmarchini** [comment]
Rebased, but I want to make a release before landing this (just in case this breaks something).

**Comment by mmarchini** [comment]
Landed in c851b9a

**Comment by mmarchini** [comment]
I missed the failing CI on Linux before landing 😕

Will open a PR to unbreak our CI soon.

**Pull request closed without merging**
