### PR TITLE
Upgrade GitHub Actions

### PR DESCRIPTION
**Pull request by cclauss**
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-node/releases
* https://github.com/codecov/codecov-action/releases

### CODE REVIEW

**Comment by No9** [comment]
Hey @cclauss thanks for the PR but this work is already covered under these two PRs
llvm - https://github.com/nodejs/llnode/pull/389 
16/18 upgrade https://github.com/nodejs/llnode/issues/399 
If you're trying for something else then please let us know or we can close this PR.

**Comment by cclauss** [comment]
Let's merely upgrade the GitHub Actions.

**Comment by No9** [comment]
Excellent - The bump of actions, especially to the official setup-node, is very useful.
As this could impact #389 from both a merge and feature perspective I'm going to land that first then merge this.
Current plan is to do the merge of 389 by the end of this week - 2022-08-21.

**Comment by No9** [comment]
Hey @cclauss 
#389 has merged - If you could rebase this I would be happy to help land

**Comment by cclauss** [comment]
Rebased.  Also fixed `runs-on:` to take a string, not an array because the runner is not self-hosted.
* https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by No9** [comment]
Hey @cclauss 
There seems to be a tests that are on the edge of the timeouts for node14 with lldb12 

Would you mind bumping https://github.com/nodejs/llnode/blob/ff75da7eb151cf8d7481eba9a1c6406a53c85ce5/test/plugin/inspect-test.js#L669 
to 30000
and https://github.com/nodejs/llnode/blob/ff75da7eb151cf8d7481eba9a1c6406a53c85ce5/test/plugin/workqueue-test.js#L29
to 60000
And set the defaults to 40000
https://github.com/nodejs/llnode/blob/ff75da7eb151cf8d7481eba9a1c6406a53c85ce5/test/common.js#L45
https://github.com/nodejs/llnode/blob/ff75da7eb151cf8d7481eba9a1c6406a53c85ce5/test/common.js#L173

Thanks

**Comment by cclauss** [comment]
@No9 Your re-review please.

**Comment by No9** [comment]
Hey @cclauss I think these have landed in 404 as you requested https://github.com/nodejs/llnode/pull/404/files#diff-f3fc934cf0d89bdf07de358896ff90f1202585df812cf606206d1830a9949811R37

**Comment by cclauss** [comment]
Closing in favor of #404

**Pull request closed without merging**
